### ISSUE TITLE
Android browser redirection issues when performing auth

### ISSUE THREAD

**Issue by TwerkyMan** [Elringus/UnityGoogleDrive#21]
Hello again. It's been a while. I've been using your plugin for a long time and i've got to say - it works almost perfectly. The time and effort you put into this is amazing. I've got a few questions about this plugin, which I couldn't answer myself and I hope you can help me :)

1. Is there a way to know if a user has cancelled or timedout the request? Because every time i cancel an auth request i get an error and the whole app just freezes.

2. Does this plugin support token saving (So that i wont have to log back every time)? My app starts the whole auth procedure quite frequently. (like 15 minutes after logging in I restart my app and have to log in again)

Anyways, without this plugin, I probably would have been at a loss, so thanks you. Take care!

**Comment by Elringus** [comment]
Hello, Thanks for the kind words!

1. When user cancels auth request the app shouldn't freeze, the request should just finish with an auth error (you can check request.IsError and request.Error properties and act accordingly in your code). It could've freezed in the previous versions, though, when a non-async http listener was used. Can you please check if you're using the latest release?  
2. It actually keeps the token in player prefs and reuses it on subsequent requests by default. I can think of two possible reasons why it's not working: 
 - Make sure you're not manually [deleting cached tokens](https://github.com/Elringus/UnityGoogleDrive#how-to-logout-or-force-user-to-loginselect-another-google-account) somewhere;
 - In case you're using the plugin in WebGL builds, the tokens will not be used due to auth method limitations.

**Comment by TwerkyMan** [comment]
Alright, I updated the plugin and here's what I've got. The token saving is working (finally), but auth error handling is still acting strange. Beofre the update, when I pressed cancel(in Google Drive login) it would redirect me to localhost. Then i would get back to my app, which would either freeze, or the button that calls auth function would stopped working.  Right now when I press cancel sing in, the Google Drive page would keep loading (basically freeze). I got back to my app, and the button which calls the login function won't do anything again. So yeah, I got 1 problem out of the way, thanks to you :)

**Comment by TwerkyMan** [comment]
I also noticed that after the update Google Drive login page freezes no matter what. When i click login it waits for the localhost, which never gets redirected to. Strage thing, but when i closed the ongoing login page, my app reacted as if i had logged on.

**Comment by Elringus** [comment]
After looking into the auth error handling code, I was able to find some issues. They're now fixed in the [latest release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.18-alpha) and you should be able to get the responses when user cancels the auth in browser. For example, I've added error checking to one of the test scripts: https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestAboutGet.cs#L42 Feel free to use it as a reference when implementing your own logic for handling request errors.

**Comment by TwerkyMan** [comment]
Thanks for assisting me with my problems :) I've updated the plugin again and some really strange things are happening. Whenever i try to login or cancel the auth, Google Drive login page loads forever until i switch back to my app. Only then the localhost will load. I don't know whether it's the plugin or my internet. Thank you so much for helping again!

**Comment by Elringus** [comment]
Is this happening in the editor or in a build? Try to clone the example repo and run the included test scripts with the latest Unity version. In case the issue will still persist, please specify the target platform, OS and Unity version you're using,

**Comment by TwerkyMan** [comment]
This is happening both in editor and in build. (PC and Android) It started when i updated the plugin to the latest version todays noon. I'm using the latest Unity version (2018.2.3...etc). I'll specify more details tomorrow if needed. Thanks in advance :)

**Comment by TwerkyMan** [comment]
Hey! It's been like a week since this proplem was posted and I was wondering if you managed to find the error? Maybe I could help somehow?

**Comment by Elringus** [comment]
Hi, Have you tried to clone the example repo and run the included test scripts with the latest Unity version? I wasn't able to reproduce the issue you've described, so I'll either need some more details to reproduce it, or a repro project to continue investigation.

**Comment by TwerkyMan** [comment]
Okay, I tried the example scenes and scripts, but i get the same error. When I click accept in Google Drive's login page it just loads forever, until i go back to Unity. And just then it redirects me to localhost. I removed my NUNIT package but it still acts the same.

**Comment by Elringus** [comment]
Well, I still can't reproduce this. Maybe the issue is network-specific (firewall, router config, etc). What OS you're using btw (Windows/Mac)?

**Comment by TwerkyMan** [comment]
I also tought that, but this happens both on my PC(Windows) and phone(Android)

**Comment by TwerkyMan** [comment]
I think this has something to do with localhost, because either I'm accepting or rejecting the authorization, Google tries to redirect to localhost, and goes on forever.

**Comment by Elringus** [comment]
Thinking about this behavior, could it be that "Run In Background" is disabled in the player settings? Though it's enabled in the repo project which you've already tested, please check it just to be sure.

**Comment by Elringus** [comment]
Actually... On mobiles it still won't work, cause it can't run in background like on standalone. It definitely worked on android and ios before without the background mode, but looks like I've changed something in one of the recent updates. I'll look into this more and update this thread with the results. Thank you for bringing this up, god knows how long it would go unnoticed, as I'm currently not using this plugin on mobiles :)

**Comment by Elringus** [comment]
I've [released an update with the fix](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.19-alpha). It should now work regardless "run in background" is available.

**Comment by TwerkyMan** [comment]
I'm sorry to say this, but the issue still persist on my Android device. It works in PC now, so that is a step forward :)

**Comment by Elringus** [comment]
Please double check you're using the latest release. I've tested it on my android tablet and it worked fine.

**Comment by TwerkyMan** [comment]
Nope, I'm using the latest release. On PC it works with and without "Run in background". On Android, it doesn't work either way...

**Comment by Elringus** [comment]
Well, then we need to find out why it's working on one android device, but not on another :) Unfortunately, I don't have enough spare time to work on this right now, so in case you or anyone else discover additional info, please share it in this thread.

**Comment by TwerkyMan** [comment]
I'm thinking that either it has something to do with my Player Settings or the phone itself. I'm using Samsung Galaxy S8 if that helps :)

**Comment by TwerkyMan** [comment]
Hey again. Today I installed an older version of my app to my phone (That version had the old version of this plugin) and it worked. The error had completely vanished. But, of course, newer versions are still experiencing this problem. Hope this helps somehow. Take care.

**Comment by TwerkyMan** [comment]
So i tested the plugins older and never version on 3 devices (Samsung Galxy S8, OnePlus 5T and Samsung Tab S). As I expected, the older version worked and the newer didn't (on all devices). Because of this, I'm thinking, maybe there is something wrong with my Unity settings? Hope this helps :)

**Comment by Elringus** [comment]
> maybe there is something wrong with my Unity settings?
You can test this by running the project from this repo.

**Comment by Elringus** [comment]
Clone the repository, open the project and run the build on the devices. This way you'll find out whether project settings have anything to do with the issue.

**Comment by TwerkyMan** [comment]
Nope, it still won't work...

**Comment by TwerkyMan** [comment]
Sorry about that last statement.. Today I opened your plugin as UnityProject and built it on my phone. it actually worked. Now i think that there is something in my Unity Project that is causing this error. Maybe a dumb setting or so. Anyway thank's for trying to help me with my not working project :)

**Comment by TwerkyMan** [comment]
Sigh.. We're not quite done yet. The plugin now works partly - It only redirects to localhost if I click the accept button fast enough. If i wait a few seconds in Google Drives login page and then click accept - I don't get redirected to localhost. Quite strange....

**Comment by Elringus** [comment]
I've tried waiting for more than a minute before clicking the accept button, but it still worked fine on my android tablet. Could it be it's still something related with your project settings or custom scripts?

**Comment by TwerkyMan** [comment]
To be honest, it probably is. What is strange tho, is that on PC it works no matter the waiting time, but on phone - nope. What is even more strange, is that i tired building your plugin as Unity Project again and noticed tge same error. I don't know what is causing this...

**Comment by TwerkyMan** [comment]
Oh alright. Thanks.

**Comment by TwerkyMan** [comment]
I checked the project again and it seems to work exactly the same way as my project does. It only works if i pres "accept button" quickly enough. This is really strange behavior...

**Comment by ddutchie** [comment]
This seems to fix auth issues on android, but breaks it for iOS?

**Comment by Elringus** [comment]
I've published a [new release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.20-alpha) with the fixes for both Android and iOS authentication issues. Please refer to the project's readme to find out how to configure the plugin to work on these platforms.
